# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - DJANGO_SETTINGS_MODULE=config.settings.testing SECRET_KEY=secret_key_for_testing_!@_56523

install:
  - pip install -U -r requirements/requirements.txt
  - pip install -U -r requirements/test_requirements.txt

# command to run tests, e.g. python setup.py test
script:
  python portland_python/manage.py test
  # py.test --flake  --cov-report term --cov pyzillow test/

after_success:
  coveralls